version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /bot
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /apps/client
    schedule:
      interval: weekly
